### ISSUE TITLE
Support Docker registry authentication in worker

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect-docker#72]
With agents and infrastructure blocks, users can configure a [DockerRegistry](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/infrastructure/container.py#L100) block that contains registry details and credentials. This allows users to connect to private registries. The Docker worker does not currently support this and so cannot pull images from a private registry unless authentication has already happened. At first I thought this might be possible via a custom pull step, but since steps are run inside the container, I don't believe that is a solution. It would be useful if we could port the registry auth code into the worker and expose it as variables.

**Comment by toby-coleman** [comment]
Another vote for this feature - we would like to migrate our flows from Prefect agents to workers, and need a way to use our Docker Registry block.

**Comment by spencersmallwood** [comment]
+1

**Comment by gerritdeen** [comment]
+1

**Comment by gc-holzapfel** [comment]
+1

**Comment by mmartsen** [comment]
+1

**Comment by dsmfreire** [comment]
+1

**Comment by kristerksat** [comment]
+1

**Comment by gc-sommer** [comment]
+1

**Comment by dsmfreire** [comment]
@desertaxle @chrisguidry I believe that the solution in #102 does not work. By providing the DockerRegistryCredentials object to a field of job_variables, the password will not be exposed upon model dump, since it's a SecretStr without the field serializer override needed for this effect (https://docs.pydantic.dev/1.10/usage/types/#secret-types). I already tried implementing it this way in my forked repo and failed due to what I just described. I do not think it is a good solution to serialize the registry password as plain text in the job variables, hence my final implementation relies on passing the name of a saved credentials block to the job_variables, which is encrypted by prefect. May you reopen this issue to discuss a better solution?
